package com.banking.audit.entity;

public enum AuditEventType {
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTRATION,
    USER_LOGIN_FAILED,
    USER_ACCOUNT_LOCKED,
    PROFILE_UPDATED,
    KYC_UPDATED,
    ACCOUNT_CREATED,
    ACCOUNT_STATUS_CHANGED,
    TRANSACTION_CREATED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    FRAUD_ALERT_CREATED,
    FRAUD_ALERT_RESOLVED,
    BENEFICIARY_ADDED,
    BENEFICIARY_REMOVED,
    ADMIN_ACTION,
    SYSTEM_ERROR
}
